[package]
name = "libchatserv"
version = "0.1.0"
authors = ["Anthony Anderson <anderson@mdhs.info>"]

[dependencies]
serde_json = "1.0"
serde_derive = "1.0"
serde = "1.0"
nats = "*"
serde_yaml = "0.7"
