[package]
name = "libchatserv"
version = "0.1.0"
authors = ["Anthony Anderson <anderson@mdhs.info>"]

[dependencies]
serde = "1.0.37"
serde_json = "1.0.13"
serde_derive = "1.0.37"
nats = "0.2.0"
serde_yaml = "0.7.3"
